package it.giacomos.android.wwwsapp.network.state;

public enum ViewType {
	TODAY, TOMORROW, TWODAYS, HOME,
	TODAY_SYMTABLE, TOMORROW_SYMTABLE, TWODAYS_SYMTABLE,
	LATEST_SKY, LATEST_TEMP, LATEST_HUMIDITY,
	LATEST_RAIN, LATEST_WIND, LATEST_PRESSURE, LATEST_SEA, LATEST_SNOW,
	LATEST_TABLE,
	DAILY_SKY, DAILY_MIN_TEMP, DAILY_MAX_TEMP, DAILY_MEAN_TEMP, DAILY_HUMIDITY,
	DAILY_RAIN, DAILY_WIND, DAILY_WIND_MAX, DAILY_PRESSURE, DAILY_SEA, DAILY_SNOW,
	DAILY_TABLE,
	RADAR, WEBCAM, 
	ACTION_CENTER_MAP, 
	REPORT, THREEDAYS, FOURDAYS, THREEDAYS_SYMTABLE, FOURDAYS_SYMTABLE
}
